Provides more descriptive vm name for Virtualbox
VTUL/InstallScripts pull request #129
Opened 2017-02-18 15:40 UTC by whunter

Allows user to specify vm name for Virtualbox and falls back to "project_name" if not defined. Useful for me so that I can identify my vm's in the Virtualbox gui.
Currently, all vm's are named similarly.
<img width="798" alt="before" src="https://cloud.githubusercontent.com/assets/1202435/23094417/8e56a12a-f5c6-11e6-900a-4b30574376ce.png">
This change allows them to be more descriptive
<img width="785" alt="after" src="https://cloud.githubusercontent.com/assets/1202435/23094425/a0f698f8-f5c6-11e6-8bc7-b55052e6894e.png">

2017-02-18 17:33 UTC, pmather requested changes
As someone who almost never looks at the VirtualBox GUI nor uses it to manage Vagrant machines, I am struggling to appreciate the need for this change. 😃 

Having said that, if you are to press ahead with this change, please make it entirely optional.  In other words, only set `vb.name` in the `virtualbox` provider if it is _explicitly_ requested in `site_secrets.yml` by having `vm_name` set to something.  Otherwise, do not set `vb.name` at all, which preserves the current behaviour.

One of the reasons setting the machine name was removed in the first place was that (IIRC) it does not allow multiple versions of the same VM to defined at the same time on the same machine.  Thus, with the above change, you would not be able to have two `iawa` VMs at the same time (even if they weren't running).  After getting an error to this effect when trying to create the second `iawa` VM, you'd have to explicitly rename it in `site_secrets.yml` before you could do so.  That, IMHO, is unnecessary extra work for those who always interact with Vagrant boxes using the `vagrant` command (which is ostensibly the "Vagrant way"), and never see what is listed inside VirtualBox.

I argue that it should be those who actually care what the VirtualBox GUI calls their VMs that should have the onus of specifying that name, not the other way around.

2017-02-18 21:00 UTC, whunter commented
@pmather This has been updated to reflect your change request. I generally use the command line to interact with vagrant also but sometimes I'll have quite a few vm's created that I would like to clean up and I lose track of which one belongs to which directory.

2017-02-19 17:30 UTC, pmather requested changes
I still think this only partially helps with locating which VirtualBox VM is where.  (I imagine you'd get to the state where you have `iawa_1`, `iawa_2`, etc. VMs listed in the VirtualBox GUI and still have little idea of where they are actually located on disk.)

For our setup, looking at the Settings -> Shared Folders path for `vagrant` will let you know where the VM project lives.  Thus, a preferable change may be to use the `customize` method (described in the "VBOXMANAGE CUSTOMIZATIONS" section of the [VirtualBox provider customisation page](https://www.vagrantup.com/docs/virtualbox/configuration.html)) to add content to the `description` metatdata for the VM.  E.g.,
```
v.customize ["modifyvm", :id, "--description", "Created from Vagrantfile in #{vagrantfile_dir}"]
```
or something similar (where `vagrantfile_dir` would be code representing the dirname of the Vagrantfile used in `vagrant up`).

This would result in Settings -> General -> Description containing useful information locating the VM.

This idea could also be extended to include other useful metadata about the VM created, e.g., the time `vagrant up` was executed, etc., so that such metadata was contained all in one place.  This could be a general place for project-related metadata about VMs.

I have no objections to your `vb.name` change, but please also add the `--description` customisation feature.  This could either be as an addition to `vb.name` or as a replacement for it.

2017-02-20 22:34 UTC, whunter commented
@pmather I've added the description customization. Seems to work as expected.

2017-02-21 00:22 UTC, pmather approved these changes
Thanks for this change.

2017-02-21 00:23 UTC, merged