add fonts to compel/binaryArts application
VTUL/InstallScripts pull request #145
Opened 2018-02-23 19:59 UTC by whunter

2018-02-26 16:57 UTC, pmather requested changes
You are referencing a handler (`clear rails cache`) that does not exist during this playbook run.

2018-02-26 16:57 UTC, pmather commented on ansible/roles/hyrax/tasks/binary-arts.yml
> +    notify: clear rails cache
The `clear rails cache` handler is missing from `ansible/roles/hyrax/handlers/main.yml`, which causes this play to fail.  The `clear rails cache` entry from `ansible/roles/sufia/handlers/main.yml` could be prepended to `ansible/roles/hyrax/handlers/main.yml` to achieve the same effect as a quick way of fixing this.

2018-02-26 20:30 UTC, whunter commented on ansible/roles/hyrax/tasks/binary-arts.yml
> +    notify: clear rails cache
@pmather I added that handler to hyrax.

2018-02-28 21:12 UTC, pmather approved these changes

2018-02-28 21:17 UTC, merged